version: '3.8'

services: 
  app: 
    build: app
    container_name: app
    tty: true
    environment:
      - CONNECTION_STRING=Server=db;Database=Dinas;User=sa;Password=1q2w3e4r@#$;Encrypt=False
    ports:
      - "5000:80"
    depends_on:
      - db
  
  db:
    build: sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"